In [100]:
import numpy as np
np.__version__

'1.26.4'

In [101]:
# Conver list intop array because array is fast compared to list
ls=[1,2,3]
np.array(ls)

array([1, 2, 3])

In [102]:
ls=[1,2,3]
arr=np.array(ls)
type(arr)

numpy.ndarray

In [103]:
arr.ndim

1

In [104]:
arr.size

3

In [105]:
arr.shape

(3,)

In [106]:
ls1=[1,2.5,6.0]
np.array(ls1)  # Converts all integers to floating



array([1. , 2.5, 6. ])

In [107]:
np.array([2,4,6,2.5, 2+5j]) # All values is converted to complex number

array([2. +0.j, 4. +0.j, 6. +0.j, 2.5+0.j, 2. +5.j])

In [108]:
np.array([2,4,6,2.5], dtype='int') # Converts all to integer

array([2, 4, 6, 2])

In [109]:
np.array([2,4,6,2.5], dtype='str') # Converts all to string but for complex we cannot convert complex to float or integer

array(['2', '4', '6', '2.5'], dtype='<U3')

In [110]:
# 3d Array
arr2=np.array([[12,43,23],
         [2,43,23],
         [120,43,23]])
arr2

array([[ 12,  43,  23],
       [  2,  43,  23],
       [120,  43,  23]])

In [111]:
arr2.ndim

2

In [112]:
np.array([[12,43,23],
         [2,43,23],
         [120,43,np.nan]])  # Used to denote missing values (np.nan)

array([[ 12.,  43.,  23.],
       [  2.,  43.,  23.],
       [120.,  43.,  nan]])

In [113]:
np.array([[12,43,23],
         [2,43,23],
         [120,43,None]])  # Used to denote missing values as object (None)

array([[12, 43, 23],
       [2, 43, 23],
       [120, 43, None]], dtype=object)

In [114]:
# list(range(1.5,11.5)) # Range fn only works with integer values not floating so we use (arange) for this
# Gives error

In [115]:
np.arange(1.5,11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [116]:
np.arange(1.5,11.5,2)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [117]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
# COnverting to 3*2
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [120]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
# COnvert n dimensional array in one dimensional
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [123]:
np.ones([2,3], dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [124]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [125]:
np.zeros([2,3,4])


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [126]:
np.full(10,7) #generate 10 elements with 7 nmumber


array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [127]:
np.full([2,3],5)


array([[5, 5, 5],
       [5, 5, 5]])

In [128]:
np.full([2,3],[7,8,9])

array([[7, 8, 9],
       [7, 8, 9]])

In [129]:
# Create Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
np.eye(3)  #eve or identity method to generate identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
np.random.randint(1,10,5) # Generates random 5 numbers between given range i.e., 1 to 10 

array([8, 5, 3, 9, 8])

In [132]:
np.random.randint(100,200,[3,4])

array([[160, 121, 154, 121],
       [180, 187, 177, 189],
       [184, 154, 148, 153]])

In [133]:
np.random.rand(5)

array([0.86169308, 0.6944672 , 0.11331974, 0.59900623, 0.15577043])

In [134]:
np.random.rand(1,10,5) #  For Unifrom distribution we use rand


array([[[0.68244466, 0.89244059, 0.53352888, 0.85798678, 0.73761597],
        [0.4948645 , 0.17399218, 0.48165201, 0.26284546, 0.63343901],
        [0.74441327, 0.81100984, 0.06624049, 0.1253379 , 0.93812334],
        [0.47766448, 0.77002673, 0.23751922, 0.40779593, 0.99006171],
        [0.7283934 , 0.54235376, 0.19435897, 0.50247752, 0.43329144],
        [0.06113204, 0.37781407, 0.87915431, 0.50374157, 0.67009407],
        [0.86951781, 0.6839612 , 0.3215719 , 0.33915225, 0.54560047],
        [0.98177515, 0.950842  , 0.91246117, 0.12080285, 0.33160162],
        [0.90998986, 0.79600397, 0.90247317, 0.68826774, 0.88924572],
        [0.2200619 , 0.79693561, 0.5759532 , 0.36751036, 0.38457401]]])

In [135]:
np.random.rand(5)  #All values from output follows normal distribution

array([0.16383542, 0.00755033, 0.98801394, 0.13288288, 0.60316367])

In [136]:
np.linspace(1,10,5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [137]:
np.linspace(2,5, retstep=True) # Gives same difference

(array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
        2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
        2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
        2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
        3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
        3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
        3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
        4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
        4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
        4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]),
 0.061224489795918366)

In [139]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [140]:
new_arr=arr.view()
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [144]:
arr[0][0]=100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [145]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [141]:
new_arr_copy=arr.copy()
new_arr_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [142]:
arr[0][0]=1000
arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [143]:
new_arr_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])